### ISSUE TITLE
Fehler bei hochlichtung

### ISSUE THREAD

**Issue by 5yn74x** [NullDev/CSZ-Bot#236]
Hier wird ein invalid User verlinkt, obwohl die ID korrekt ist. Liegt es an dem "!", da in den PNs und außerhalb des Servercontext kein Nickname gesetzt ist?

https://github.com/NullDev/CSZ-Bot/blob/f800125ab7fbc0200e749bd79b34f95572651576/src/commands/hilfe.ts#L74

**Comment by NullDev** [comment]
Da können wir eigentlich sowieso den CSZ-Bot channel verlinken. `<#902960751222853702>`
