### ISSUE TITLE
.mock vermockt emojis

### ISSUE THREAD

**Issue by s0LA1337** [NullDev/CSZ-Bot#254]
## Fehler Report

**Fehler beschreibung:** <bR>
Eine genaue beschreibung des Fehlers
wenn `.mock` ein emoji beinhaltet, wird dieses weggemockt.

**Reproduzierung:** <bR>
Wie kann man den Fehler reproduzieren?
`.mock <a:BOOBA:831436659169689642>`
-> :BoObA: wird halt dann weggemockt.

**Erwartetes Resultat:** <bR>
Was sollte eigentlich passieren?
das emoji bleibt erhalten.

**Comment by Feluin** [comment]
https://discord.com/channels/618781839338897443/620729211442692106/1023676891787448454 
Getest, works as intendet. RTFM und so. Emojis von der CSZ werden korrekt angezeigt. Für alle anderen emojis müsste der dönerjesus sich auf auf den anderen server befinden.
