### ISSUE TITLE
Log im Woistext wer joined und leaved

### ISSUE THREAD

**Issue by PatchRequest** [NullDev/CSZ-Bot#259]
## Funktions Wunsch
Log im Woistext wer joined und leaved

**Funktionen:** <br>
Beim Join in woistext schreibt der bot das in den channel als log. Kommt voll oft vor man hört jemand ist geleaved oder gejoined und keiner weiß wer.

Baue das Feature selbst ein wollte nur Clean hier schonmal nen Issue dafür aufmachen

**Comment by PatchRequest** [comment]
![image](https://user-images.githubusercontent.com/47796889/191816281-113c45db-718f-490c-9a86-8f10fda9dd16.png)
Sieht dann so aus

**Comment by PatchRequest** [comment]
Da schon nen paar geheult haben bau ich ein das die Nachricht nach x minuten autodeleted wird

**Comment by twobiers** [comment]
> Da schon nen paar geheult haben bau ich ein das die Nachricht nach x minuten autodeleted wird

Wat für Lelleks

**Comment by holzmaster** [comment]
Dagegen
