### ISSUE TITLE
insta (auch tiktok?) command broken

### ISSUE THREAD

**Issue by arellak** [NullDev/CSZ-Bot#316]
Insta lädt ihren Scheiß wohl dynamisch und dadurch ist es schwieriger direkt an den Inhalt zu kommen
Und die TikTok Library ist wohl nicht auf dem neusten Stand bzw es gibt noch kein neues Update

**Comment by twobiers** [comment]
Ja dicker, hab geregelt.

**Comment by arellak** [comment]
Hast du gut gemacht, bin stolz auf dich :3
