### ISSUE TITLE
Geburtstag ändern

### ISSUE THREAD

**Issue by arellak** [NullDev/CSZ-Bot#413]
Bisher hat man reingeschissen, wenn man seinen Geburtstag falsch eingetragen hat.
Kann man jetzt unterschiedlich lösen:
1. User kann beliebig oft selber ändern (kann man leicht abusen und so)
2. User kann n mal das Datum selber ändern (kann man weniger leicht abusen bzw. nur n mal - muss aber wieder extra gespeichert werden)
3. Mods/Admins schalten es für den User frei, dass er das Datum ändern kann und dann hat er quasi einen Freiversuch und danach ist es wieder gelockt.

@twobiers

**Comment by twobiers** [comment]
Wenn du Lust hast das zu implementieren, such dir was aus und mach. Finde da gibt es keine schlechte Lösung.

Ich bin der Meinung dass es so ein Feature nicht braucht. Wir haben genau einen Fall, wo das zutrifft und das wären auch nur 2 Minuten Arbeit in der Datenbank händisch zu aktualisieren (muss nur einer machen lol).

**Comment by holzmaster** [comment]
Is jetzt ein upsert. Wer meint, jeden Tag sein Geburtstag zu ändern, hat eh pech
