### ISSUE TITLE
Backup von Emotes / Emote-Zähler

### ISSUE THREAD

**Issue by twobiers** [NullDev/CSZ-Bot#453]
### Beschreibung

Würde gerne von den Emotes regelmäßige backups fahren, damit man (irrtümlich) gelöschte emotes restoren kann. Das ist vor allem bei Emotes sinnvoll, die manuell erstellt wurden.

In dem Zuge wäre für die Emotifizierer auch geil die Verwendung von Emotes zu zählen, sodass die am wenigsten verwendeten identifiziert werden können.

### Pro

- Falls ein Emote gelöscht wird, kann es wiederhergestellt werden
- Originaldateien verloren -> kein Problem, einfach restoren

### Contra

- Hemmschwelle zum Entfernen sinkt

### Ich möchte das Feature bauen

- [X] Ja
- [X] Nein
- [ ] Mit Hilfe

### Papierkram

- [X] Ich habe die AGB gelesen und möchte den Newsletter abonnieren
- [X] Ich stimme der Verwendung von Cookies zu

**Comment by holzmaster** [comment]
Benutzung von Emotes in Nachrichten wird gezählt. Anmerkungen:

- Das Datenmodell kann nicht handlen, wenn eine Nachricht einen Emote mehrfach enthält (aktuell nur wegen eines Unique-Indexes auf `["messageId", "emoteId", "usedByUserId", "isReaction", "deletedAt"]`)
- Nur für dich und mich aktiviert, weil noch zu klären is, ob das opt-in, opt-out oder was auch immer sein soll
- reactions werden gefangen, aber das entfernen von reactions noch nicht
- bearbeitete nachrichten auch nicht

Wenn das feature fertig is, könnte man die DB mal initial beladen (oder generell beim bot-startup checken, ob alles schon da ist)

**Comment by twobiers** [comment]
Negativ.

#closed
