### ISSUE TITLE
TimeZone Bug #2

### ISSUE THREAD

**Issue by NullDev** [NullDev/CSZ-Bot#64]
TimeZone Fix. 
Mein issue https://github.com/NullDev/CSC-Bot/issues/60 wurde nur sehr hacky gefixed indem eine falsche Zeit im Cron hinterlegt wurde. Siehe:

https://github.com/NullDev/CSC-Bot/pull/61/commits/747a674429cb8d67e2292b0982253b454bb47b4f

<sub>danke @diewellenlaenge </sub>

---

Problem ist, Geburtstage sind ebenfalls einen ganzen Tag verzögert.

**Comment by NullDev** [comment]
Und for the lulz:

**Comment by tobi6112** [comment]
Hallo 👋 erste 1️⃣ Rückmeldung 🔈: Container 🚢 hat jetzt richtige Zeitzone ⌚🥳, aber kp 😕 ob das was bringt 🤸‍♂️ 
```sh
root@csc:/home/csc# docker exec -it 704b93656b22 date
Mon Aug  2 10:21:06 CEST 2021
```

**Comment by diewellenlaenge** [comment]
Bitte danach den wundervollen Hack wieder löschen/entfernen (https://github.com/NullDev/CSC-Bot/commit/747a674429cb8d67e2292b0982253b454bb47b4f).
